-- Seed: populate giros_modulos / giros_terminologia / giros_campos from
-- the hardcoded constants in public/salvadorex-pos.html (INDUSTRY_PROFILES,
-- INDUSTRY_TERMS, INDUSTRY_PRODUCT_FIELDS). 2026-05-09. Idempotent.
-- Generated by Claude — manual edits OK after running once.

-- ─────────────────────────────────────────────────────────────────────────
-- Unique indexes (no-op if already present)
-- ─────────────────────────────────────────────────────────────────────────
CREATE UNIQUE INDEX IF NOT EXISTS giros_modulos_uniq       ON giros_modulos(giro_slug, modulo);
CREATE UNIQUE INDEX IF NOT EXISTS giros_terminologia_uniq  ON giros_terminologia(giro_slug, clave);
CREATE UNIQUE INDEX IF NOT EXISTS giros_campos_uniq        ON giros_campos(giro_slug, modal, campo);

-- ─────────────────────────────────────────────────────────────────────────
-- SECTION 1: giros_modulos
-- 38 giros × (10 PROFILE_GENERIC modules + per-giro extras)
-- All values are activo=true; absence in source = row not seeded.
-- ─────────────────────────────────────────────────────────────────────────
BEGIN;

INSERT INTO giros_modulos (giro_slug, modulo, activo, orden) VALUES
-- abarrotes (20)
('abarrotes','pos',true,10),('abarrotes','dashboard',true,20),('abarrotes','apertura',true,30),('abarrotes','corte',true,40),('abarrotes','ventas',true,50),('abarrotes','reportes',true,60),('abarrotes','clientes',true,70),('abarrotes','usuarios',true,80),('abarrotes','config',true,90),('abarrotes','devoluciones',true,100),('abarrotes','inventario',true,110),('abarrotes','kardex',true,120),('abarrotes','credito',true,130),('abarrotes','proveedores',true,140),('abarrotes','recargas',true,150),('abarrotes','servicios',true,160),('abarrotes','promociones',true,170),('abarrotes','departamentos',true,180),('abarrotes','sugeridas',true,190),('abarrotes','actualizador',true,200),
-- minisuper (19)
('minisuper','pos',true,10),('minisuper','dashboard',true,20),('minisuper','apertura',true,30),('minisuper','corte',true,40),('minisuper','ventas',true,50),('minisuper','reportes',true,60),('minisuper','clientes',true,70),('minisuper','usuarios',true,80),('minisuper','config',true,90),('minisuper','devoluciones',true,100),('minisuper','inventario',true,110),('minisuper','kardex',true,120),('minisuper','credito',true,130),('minisuper','proveedores',true,140),('minisuper','recargas',true,150),('minisuper','servicios',true,160),('minisuper','promociones',true,170),('minisuper','departamentos',true,180),('minisuper','actualizador',true,190),
-- tienda-conveniencia (18)
('tienda-conveniencia','pos',true,10),('tienda-conveniencia','dashboard',true,20),('tienda-conveniencia','apertura',true,30),('tienda-conveniencia','corte',true,40),('tienda-conveniencia','ventas',true,50),('tienda-conveniencia','reportes',true,60),('tienda-conveniencia','clientes',true,70),('tienda-conveniencia','usuarios',true,80),('tienda-conveniencia','config',true,90),('tienda-conveniencia','devoluciones',true,100),('tienda-conveniencia','inventario',true,110),('tienda-conveniencia','kardex',true,120),('tienda-conveniencia','proveedores',true,130),('tienda-conveniencia','recargas',true,140),('tienda-conveniencia','servicios',true,150),('tienda-conveniencia','promociones',true,160),('tienda-conveniencia','departamentos',true,170),('tienda-conveniencia','actualizador',true,180),
-- farmacia (19)
('farmacia','pos',true,10),('farmacia','dashboard',true,20),('farmacia','apertura',true,30),('farmacia','corte',true,40),('farmacia','ventas',true,50),('farmacia','reportes',true,60),('farmacia','clientes',true,70),('farmacia','usuarios',true,80),('farmacia','config',true,90),('farmacia','devoluciones',true,100),('farmacia','inventario',true,110),('farmacia','kardex',true,120),('farmacia','credito',true,130),('farmacia','proveedores',true,140),('farmacia','facturacion',true,150),('farmacia','promociones',true,160),('farmacia','departamentos',true,170),('farmacia','sugeridas',true,180),('farmacia','actualizador',true,190),
-- fruteria (13)
('fruteria','pos',true,10),('fruteria','dashboard',true,20),('fruteria','apertura',true,30),('fruteria','corte',true,40),('fruteria','ventas',true,50),('fruteria','reportes',true,60),('fruteria','clientes',true,70),('fruteria','usuarios',true,80),('fruteria','config',true,90),('fruteria','devoluciones',true,100),('fruteria','inventario',true,110),('fruteria','departamentos',true,120),('fruteria','promociones',true,130),
-- carniceria (14)
('carniceria','pos',true,10),('carniceria','dashboard',true,20),('carniceria','apertura',true,30),('carniceria','corte',true,40),('carniceria','ventas',true,50),('carniceria','reportes',true,60),('carniceria','clientes',true,70),('carniceria','usuarios',true,80),('carniceria','config',true,90),('carniceria','devoluciones',true,100),('carniceria','inventario',true,110),('carniceria','departamentos',true,120),('carniceria','promociones',true,130),('carniceria','proveedores',true,140),
-- polleria (14)
('polleria','pos',true,10),('polleria','dashboard',true,20),('polleria','apertura',true,30),('polleria','corte',true,40),('polleria','ventas',true,50),('polleria','reportes',true,60),('polleria','clientes',true,70),('polleria','usuarios',true,80),('polleria','config',true,90),('polleria','devoluciones',true,100),('polleria','inventario',true,110),('polleria','departamentos',true,120),('polleria','promociones',true,130),('polleria','proveedores',true,140),
-- tortilleria (13)
('tortilleria','pos',true,10),('tortilleria','dashboard',true,20),('tortilleria','apertura',true,30),('tortilleria','corte',true,40),('tortilleria','ventas',true,50),('tortilleria','reportes',true,60),('tortilleria','clientes',true,70),('tortilleria','usuarios',true,80),('tortilleria','config',true,90),('tortilleria','devoluciones',true,100),('tortilleria','inventario',true,110),('tortilleria','departamentos',true,120),('tortilleria','promociones',true,130),
-- panaderia (13)
('panaderia','pos',true,10),('panaderia','dashboard',true,20),('panaderia','apertura',true,30),('panaderia','corte',true,40),('panaderia','ventas',true,50),('panaderia','reportes',true,60),('panaderia','clientes',true,70),('panaderia','usuarios',true,80),('panaderia','config',true,90),('panaderia','devoluciones',true,100),('panaderia','inventario',true,110),('panaderia','departamentos',true,120),('panaderia','promociones',true,130),
-- pasteleria (13)
('pasteleria','pos',true,10),('pasteleria','dashboard',true,20),('pasteleria','apertura',true,30),('pasteleria','corte',true,40),('pasteleria','ventas',true,50),('pasteleria','reportes',true,60),('pasteleria','clientes',true,70),('pasteleria','usuarios',true,80),('pasteleria','config',true,90),('pasteleria','devoluciones',true,100),('pasteleria','inventario',true,110),('pasteleria','departamentos',true,120),('pasteleria','promociones',true,130),
-- cafeteria (13)
('cafeteria','pos',true,10),('cafeteria','dashboard',true,20),('cafeteria','apertura',true,30),('cafeteria','corte',true,40),('cafeteria','ventas',true,50),('cafeteria','reportes',true,60),('cafeteria','clientes',true,70),('cafeteria','usuarios',true,80),('cafeteria','config',true,90),('cafeteria','devoluciones',true,100),('cafeteria','inventario',true,110),('cafeteria','departamentos',true,120),('cafeteria','promociones',true,130),
-- restaurante (12)
('restaurante','pos',true,10),('restaurante','dashboard',true,20),('restaurante','apertura',true,30),('restaurante','corte',true,40),('restaurante','ventas',true,50),('restaurante','reportes',true,60),('restaurante','clientes',true,70),('restaurante','usuarios',true,80),('restaurante','config',true,90),('restaurante','devoluciones',true,100),('restaurante','departamentos',true,110),('restaurante','promociones',true,120),
-- taqueria (12)
('taqueria','pos',true,10),('taqueria','dashboard',true,20),('taqueria','apertura',true,30),('taqueria','corte',true,40),('taqueria','ventas',true,50),('taqueria','reportes',true,60),('taqueria','clientes',true,70),('taqueria','usuarios',true,80),('taqueria','config',true,90),('taqueria','devoluciones',true,100),('taqueria','departamentos',true,110),('taqueria','promociones',true,120),
-- pizzeria (12)
('pizzeria','pos',true,10),('pizzeria','dashboard',true,20),('pizzeria','apertura',true,30),('pizzeria','corte',true,40),('pizzeria','ventas',true,50),('pizzeria','reportes',true,60),('pizzeria','clientes',true,70),('pizzeria','usuarios',true,80),('pizzeria','config',true,90),('pizzeria','devoluciones',true,100),('pizzeria','departamentos',true,110),('pizzeria','promociones',true,120),
-- heladeria (13)
('heladeria','pos',true,10),('heladeria','dashboard',true,20),('heladeria','apertura',true,30),('heladeria','corte',true,40),('heladeria','ventas',true,50),('heladeria','reportes',true,60),('heladeria','clientes',true,70),('heladeria','usuarios',true,80),('heladeria','config',true,90),('heladeria','devoluciones',true,100),('heladeria','inventario',true,110),('heladeria','departamentos',true,120),('heladeria','promociones',true,130),
-- jugos_naturales (13)
('jugos_naturales','pos',true,10),('jugos_naturales','dashboard',true,20),('jugos_naturales','apertura',true,30),('jugos_naturales','corte',true,40),('jugos_naturales','ventas',true,50),('jugos_naturales','reportes',true,60),('jugos_naturales','clientes',true,70),('jugos_naturales','usuarios',true,80),('jugos_naturales','config',true,90),('jugos_naturales','devoluciones',true,100),('jugos_naturales','inventario',true,110),('jugos_naturales','departamentos',true,120),('jugos_naturales','promociones',true,130),
-- jugos-naturales (13)
('jugos-naturales','pos',true,10),('jugos-naturales','dashboard',true,20),('jugos-naturales','apertura',true,30),('jugos-naturales','corte',true,40),('jugos-naturales','ventas',true,50),('jugos-naturales','reportes',true,60),('jugos-naturales','clientes',true,70),('jugos-naturales','usuarios',true,80),('jugos-naturales','config',true,90),('jugos-naturales','devoluciones',true,100),('jugos-naturales','inventario',true,110),('jugos-naturales','departamentos',true,120),('jugos-naturales','promociones',true,130),
-- barberia (12)
('barberia','pos',true,10),('barberia','dashboard',true,20),('barberia','apertura',true,30),('barberia','corte',true,40),('barberia','ventas',true,50),('barberia','reportes',true,60),('barberia','clientes',true,70),('barberia','usuarios',true,80),('barberia','config',true,90),('barberia','devoluciones',true,100),('barberia','servicios',true,110),('barberia','promociones',true,120),
-- salon-belleza (13)
('salon-belleza','pos',true,10),('salon-belleza','dashboard',true,20),('salon-belleza','apertura',true,30),('salon-belleza','corte',true,40),('salon-belleza','ventas',true,50),('salon-belleza','reportes',true,60),('salon-belleza','clientes',true,70),('salon-belleza','usuarios',true,80),('salon-belleza','config',true,90),('salon-belleza','devoluciones',true,100),('salon-belleza','servicios',true,110),('salon-belleza','promociones',true,120),('salon-belleza','inventario',true,130),
-- nails (13)
('nails','pos',true,10),('nails','dashboard',true,20),('nails','apertura',true,30),('nails','corte',true,40),('nails','ventas',true,50),('nails','reportes',true,60),('nails','clientes',true,70),('nails','usuarios',true,80),('nails','config',true,90),('nails','devoluciones',true,100),('nails','servicios',true,110),('nails','promociones',true,120),('nails','inventario',true,130),
-- spa (12)
('spa','pos',true,10),('spa','dashboard',true,20),('spa','apertura',true,30),('spa','corte',true,40),('spa','ventas',true,50),('spa','reportes',true,60),('spa','clientes',true,70),('spa','usuarios',true,80),('spa','config',true,90),('spa','devoluciones',true,100),('spa','servicios',true,110),('spa','promociones',true,120),
-- veterinaria (15)
('veterinaria','pos',true,10),('veterinaria','dashboard',true,20),('veterinaria','apertura',true,30),('veterinaria','corte',true,40),('veterinaria','ventas',true,50),('veterinaria','reportes',true,60),('veterinaria','clientes',true,70),('veterinaria','usuarios',true,80),('veterinaria','config',true,90),('veterinaria','devoluciones',true,100),('veterinaria','inventario',true,110),('veterinaria','credito',true,120),('veterinaria','facturacion',true,130),('veterinaria','promociones',true,140),('veterinaria','servicios',true,150),
-- clinica-dental (14)
('clinica-dental','pos',true,10),('clinica-dental','dashboard',true,20),('clinica-dental','apertura',true,30),('clinica-dental','corte',true,40),('clinica-dental','ventas',true,50),('clinica-dental','reportes',true,60),('clinica-dental','clientes',true,70),('clinica-dental','usuarios',true,80),('clinica-dental','config',true,90),('clinica-dental','devoluciones',true,100),('clinica-dental','inventario',true,110),('clinica-dental','credito',true,120),('clinica-dental','facturacion',true,130),('clinica-dental','servicios',true,140),
-- optica (13)
('optica','pos',true,10),('optica','dashboard',true,20),('optica','apertura',true,30),('optica','corte',true,40),('optica','ventas',true,50),('optica','reportes',true,60),('optica','clientes',true,70),('optica','usuarios',true,80),('optica','config',true,90),('optica','devoluciones',true,100),('optica','inventario',true,110),('optica','credito',true,120),('optica','facturacion',true,130),
-- ropa (18)
('ropa','pos',true,10),('ropa','dashboard',true,20),('ropa','apertura',true,30),('ropa','corte',true,40),('ropa','ventas',true,50),('ropa','reportes',true,60),('ropa','clientes',true,70),('ropa','usuarios',true,80),('ropa','config',true,90),('ropa','devoluciones',true,100),('ropa','inventario',true,110),('ropa','kardex',true,120),('ropa','credito',true,130),('ropa','proveedores',true,140),('ropa','departamentos',true,150),('ropa','promociones',true,160),('ropa','cotizaciones',true,170),('ropa','facturacion',true,180),
-- tienda-ropa (18)
('tienda-ropa','pos',true,10),('tienda-ropa','dashboard',true,20),('tienda-ropa','apertura',true,30),('tienda-ropa','corte',true,40),('tienda-ropa','ventas',true,50),('tienda-ropa','reportes',true,60),('tienda-ropa','clientes',true,70),('tienda-ropa','usuarios',true,80),('tienda-ropa','config',true,90),('tienda-ropa','devoluciones',true,100),('tienda-ropa','inventario',true,110),('tienda-ropa','kardex',true,120),('tienda-ropa','credito',true,130),('tienda-ropa','proveedores',true,140),('tienda-ropa','departamentos',true,150),('tienda-ropa','promociones',true,160),('tienda-ropa','cotizaciones',true,170),('tienda-ropa','facturacion',true,180),
-- zapateria (16)
('zapateria','pos',true,10),('zapateria','dashboard',true,20),('zapateria','apertura',true,30),('zapateria','corte',true,40),('zapateria','ventas',true,50),('zapateria','reportes',true,60),('zapateria','clientes',true,70),('zapateria','usuarios',true,80),('zapateria','config',true,90),('zapateria','devoluciones',true,100),('zapateria','inventario',true,110),('zapateria','kardex',true,120),('zapateria','credito',true,130),('zapateria','proveedores',true,140),('zapateria','departamentos',true,150),('zapateria','promociones',true,160),
-- muebleria (17)
('muebleria','pos',true,10),('muebleria','dashboard',true,20),('muebleria','apertura',true,30),('muebleria','corte',true,40),('muebleria','ventas',true,50),('muebleria','reportes',true,60),('muebleria','clientes',true,70),('muebleria','usuarios',true,80),('muebleria','config',true,90),('muebleria','devoluciones',true,100),('muebleria','inventario',true,110),('muebleria','kardex',true,120),('muebleria','credito',true,130),('muebleria','proveedores',true,140),('muebleria','cotizaciones',true,150),('muebleria','facturacion',true,160),('muebleria','promociones',true,170),
-- papeleria (17)
('papeleria','pos',true,10),('papeleria','dashboard',true,20),('papeleria','apertura',true,30),('papeleria','corte',true,40),('papeleria','ventas',true,50),('papeleria','reportes',true,60),('papeleria','clientes',true,70),('papeleria','usuarios',true,80),('papeleria','config',true,90),('papeleria','devoluciones',true,100),('papeleria','inventario',true,110),('papeleria','kardex',true,120),('papeleria','proveedores',true,130),('papeleria','departamentos',true,140),('papeleria','promociones',true,150),('papeleria','cotizaciones',true,160),('papeleria','recargas',true,170),
-- ferreteria (18)
('ferreteria','pos',true,10),('ferreteria','dashboard',true,20),('ferreteria','apertura',true,30),('ferreteria','corte',true,40),('ferreteria','ventas',true,50),('ferreteria','reportes',true,60),('ferreteria','clientes',true,70),('ferreteria','usuarios',true,80),('ferreteria','config',true,90),('ferreteria','devoluciones',true,100),('ferreteria','inventario',true,110),('ferreteria','kardex',true,120),('ferreteria','credito',true,130),('ferreteria','proveedores',true,140),('ferreteria','departamentos',true,150),('ferreteria','promociones',true,160),('ferreteria','cotizaciones',true,170),('ferreteria','sugeridas',true,180),
-- refaccionaria (17)
('refaccionaria','pos',true,10),('refaccionaria','dashboard',true,20),('refaccionaria','apertura',true,30),('refaccionaria','corte',true,40),('refaccionaria','ventas',true,50),('refaccionaria','reportes',true,60),('refaccionaria','clientes',true,70),('refaccionaria','usuarios',true,80),('refaccionaria','config',true,90),('refaccionaria','devoluciones',true,100),('refaccionaria','inventario',true,110),('refaccionaria','kardex',true,120),('refaccionaria','credito',true,130),('refaccionaria','proveedores',true,140),('refaccionaria','cotizaciones',true,150),('refaccionaria','sugeridas',true,160),('refaccionaria','facturacion',true,170),
-- taller-mecanico (14)
('taller-mecanico','pos',true,10),('taller-mecanico','dashboard',true,20),('taller-mecanico','apertura',true,30),('taller-mecanico','corte',true,40),('taller-mecanico','ventas',true,50),('taller-mecanico','reportes',true,60),('taller-mecanico','clientes',true,70),('taller-mecanico','usuarios',true,80),('taller-mecanico','config',true,90),('taller-mecanico','devoluciones',true,100),('taller-mecanico','servicios',true,110),('taller-mecanico','cotizaciones',true,120),('taller-mecanico','credito',true,130),('taller-mecanico','facturacion',true,140),
-- carwash (12)
('carwash','pos',true,10),('carwash','dashboard',true,20),('carwash','apertura',true,30),('carwash','corte',true,40),('carwash','ventas',true,50),('carwash','reportes',true,60),('carwash','clientes',true,70),('carwash','usuarios',true,80),('carwash','config',true,90),('carwash','devoluciones',true,100),('carwash','servicios',true,110),('carwash','promociones',true,120),
-- purificadora (12)
('purificadora','pos',true,10),('purificadora','dashboard',true,20),('purificadora','apertura',true,30),('purificadora','corte',true,40),('purificadora','ventas',true,50),('purificadora','reportes',true,60),('purificadora','clientes',true,70),('purificadora','usuarios',true,80),('purificadora','config',true,90),('purificadora','devoluciones',true,100),('purificadora','inventario',true,110),('purificadora','credito',true,120),
-- lavanderia (12)
('lavanderia','pos',true,10),('lavanderia','dashboard',true,20),('lavanderia','apertura',true,30),('lavanderia','corte',true,40),('lavanderia','ventas',true,50),('lavanderia','reportes',true,60),('lavanderia','clientes',true,70),('lavanderia','usuarios',true,80),('lavanderia','config',true,90),('lavanderia','devoluciones',true,100),('lavanderia','servicios',true,110),('lavanderia','promociones',true,120),
-- gimnasio (12)
('gimnasio','pos',true,10),('gimnasio','dashboard',true,20),('gimnasio','apertura',true,30),('gimnasio','corte',true,40),('gimnasio','ventas',true,50),('gimnasio','reportes',true,60),('gimnasio','clientes',true,70),('gimnasio','usuarios',true,80),('gimnasio','config',true,90),('gimnasio','devoluciones',true,100),('gimnasio','servicios',true,110),('gimnasio','promociones',true,120),
-- sabanas_premium (15)
('sabanas_premium','pos',true,10),('sabanas_premium','dashboard',true,20),('sabanas_premium','apertura',true,30),('sabanas_premium','corte',true,40),('sabanas_premium','ventas',true,50),('sabanas_premium','reportes',true,60),('sabanas_premium','clientes',true,70),('sabanas_premium','usuarios',true,80),('sabanas_premium','config',true,90),('sabanas_premium','devoluciones',true,100),('sabanas_premium','inventario',true,110),('sabanas_premium','kardex',true,120),('sabanas_premium','proveedores',true,130),('sabanas_premium','departamentos',true,140),('sabanas_premium','promociones',true,150),
-- floreria (16)
('floreria','pos',true,10),('floreria','dashboard',true,20),('floreria','apertura',true,30),('floreria','corte',true,40),('floreria','ventas',true,50),('floreria','reportes',true,60),('floreria','clientes',true,70),('floreria','usuarios',true,80),('floreria','config',true,90),('floreria','devoluciones',true,100),('floreria','inventario',true,110),('floreria','departamentos',true,120),('floreria','cotizaciones',true,130),('floreria','servicios',true,140),('floreria','promociones',true,150),('floreria','proveedores',true,160)
ON CONFLICT (giro_slug, modulo) DO UPDATE SET
  activo = EXCLUDED.activo,
  orden = EXCLUDED.orden,
  updated_at = now();

COMMIT;

-- ─────────────────────────────────────────────────────────────────────────
-- SECTION 2: giros_terminologia
-- 27 giros × 5 claves (cliente, venta, ticket, inventario, producto) = 135 rows
-- valor_singular = best-effort Spanish singular (without emoji);
-- valor_plural = original value (without emoji), or same as singular when N/A.
-- ─────────────────────────────────────────────────────────────────────────
BEGIN;

INSERT INTO giros_terminologia (giro_slug, clave, valor_singular, valor_plural) VALUES
-- farmacia
('farmacia','cliente','Paciente','Pacientes'),
('farmacia','venta','Vender','Vender'),
('farmacia','ticket','Receta','Recetas'),
('farmacia','inventario','Medicamento','Medicamentos'),
('farmacia','producto','Medicamento','Medicamentos'),
-- veterinaria
('veterinaria','cliente','Tutor','Tutores'),
('veterinaria','venta','Vender','Vender'),
('veterinaria','ticket','Historial','Historial'),
('veterinaria','inventario','Medicamento','Medicamentos'),
('veterinaria','producto','Medicamento/Servicio','Medicamentos/Servicios'),
-- clinica-dental
('clinica-dental','cliente','Paciente','Pacientes'),
('clinica-dental','venta','Cobrar','Cobrar'),
('clinica-dental','ticket','Historial','Historial'),
('clinica-dental','inventario','Material','Materiales'),
('clinica-dental','producto','Tratamiento','Tratamientos'),
-- optica
('optica','cliente','Paciente','Pacientes'),
('optica','venta','Vender','Vender'),
('optica','ticket','Receta','Recetas'),
('optica','inventario','Armazón','Armazones'),
('optica','producto','Armazón','Armazones'),
-- refaccionaria
('refaccionaria','cliente','Cliente','Clientes'),
('refaccionaria','venta','Vender','Vender'),
('refaccionaria','ticket','Nota','Notas'),
('refaccionaria','inventario','Refacción','Refacciones'),
('refaccionaria','producto','Refacción','Refacciones'),
-- taller-mecanico
('taller-mecanico','cliente','Cliente','Clientes'),
('taller-mecanico','venta','Servicio','Servicios'),
('taller-mecanico','ticket','Orden','Órdenes'),
('taller-mecanico','inventario','Refacción','Refacciones'),
('taller-mecanico','producto','Servicio/Refacción','Servicios/Refacciones'),
-- restaurante
('restaurante','cliente','Comensal','Comensales'),
('restaurante','venta','Cuenta','Cuentas'),
('restaurante','ticket','Cuenta','Cuentas'),
('restaurante','inventario','Platillo','Platillos'),
('restaurante','producto','Platillo','Platillos'),
-- taqueria
('taqueria','cliente','Comensal','Comensales'),
('taqueria','venta','Cobrar','Cobrar'),
('taqueria','ticket','Cuenta','Cuentas'),
('taqueria','inventario','Producto','Productos'),
('taqueria','producto','Platillo','Platillos'),
-- cafeteria
('cafeteria','cliente','Cliente','Clientes'),
('cafeteria','venta','Vender','Vender'),
('cafeteria','ticket','Ticket','Tickets'),
('cafeteria','inventario','Producto','Productos'),
('cafeteria','producto','Producto','Productos'),
-- panaderia
('panaderia','cliente','Cliente','Clientes'),
('panaderia','venta','Vender','Vender'),
('panaderia','ticket','Ticket','Tickets'),
('panaderia','inventario','Pan','Panes'),
('panaderia','producto','Pan','Panes'),
-- pasteleria
('pasteleria','cliente','Cliente','Clientes'),
('pasteleria','venta','Vender','Vender'),
('pasteleria','ticket','Ticket','Tickets'),
('pasteleria','inventario','Pastel','Pasteles'),
('pasteleria','producto','Pastel','Pasteles'),
-- barberia
('barberia','cliente','Cliente','Clientes'),
('barberia','venta','Cita','Citas'),
('barberia','ticket','Cita','Citas'),
('barberia','inventario','Servicio','Servicios'),
('barberia','producto','Servicio','Servicios'),
-- salon-belleza
('salon-belleza','cliente','Cliente','Clientes'),
('salon-belleza','venta','Cita','Citas'),
('salon-belleza','ticket','Cita','Citas'),
('salon-belleza','inventario','Servicio','Servicios'),
('salon-belleza','producto','Servicio','Servicios'),
-- spa
('spa','cliente','Huésped','Huéspedes'),
('spa','venta','Cita','Citas'),
('spa','ticket','Reserva','Reservas'),
('spa','inventario','Servicio','Servicios'),
('spa','producto','Servicio','Servicios'),
-- gimnasio
('gimnasio','cliente','Miembro','Miembros'),
('gimnasio','venta','Inscribir','Inscribir'),
('gimnasio','ticket','Membresía','Membresías'),
('gimnasio','inventario','Plan','Planes'),
('gimnasio','producto','Plan','Planes'),
-- hotel
('hotel','cliente','Huésped','Huéspedes'),
('hotel','venta','Reservar','Reservar'),
('hotel','ticket','Reserva','Reservas'),
('hotel','inventario','Habitación','Habitaciones'),
('hotel','producto','Habitación','Habitaciones'),
-- floreria
('floreria','cliente','Cliente','Clientes'),
('floreria','venta','Vender','Vender'),
('floreria','ticket','Nota','Notas'),
('floreria','inventario','Arreglo','Arreglos'),
('floreria','producto','Arreglo','Arreglos'),
-- fruteria
('fruteria','cliente','Cliente','Clientes'),
('fruteria','venta','Vender','Vender'),
('fruteria','ticket','Ticket','Tickets'),
('fruteria','inventario','Fruta','Frutas'),
('fruteria','producto','Producto','Productos'),
-- carniceria
('carniceria','cliente','Cliente','Clientes'),
('carniceria','venta','Vender','Vender'),
('carniceria','ticket','Ticket','Tickets'),
('carniceria','inventario','Corte','Cortes'),
('carniceria','producto','Corte','Cortes'),
-- polleria
('polleria','cliente','Cliente','Clientes'),
('polleria','venta','Vender','Vender'),
('polleria','ticket','Ticket','Tickets'),
('polleria','inventario','Producto','Productos'),
('polleria','producto','Producto','Productos'),
-- ferreteria
('ferreteria','cliente','Cliente','Clientes'),
('ferreteria','venta','Vender','Vender'),
('ferreteria','ticket','Nota','Notas'),
('ferreteria','inventario','Herramienta','Herramientas'),
('ferreteria','producto','Herramienta','Herramientas'),
-- papeleria
('papeleria','cliente','Cliente','Clientes'),
('papeleria','venta','Vender','Vender'),
('papeleria','ticket','Ticket','Tickets'),
('papeleria','inventario','Artículo','Artículos'),
('papeleria','producto','Artículo','Artículos'),
-- ropa
('ropa','cliente','Cliente','Clientes'),
('ropa','venta','Vender','Vender'),
('ropa','ticket','Ticket','Tickets'),
('ropa','inventario','Prenda','Prendas'),
('ropa','producto','Prenda','Prendas'),
-- tienda-ropa
('tienda-ropa','cliente','Cliente','Clientes'),
('tienda-ropa','venta','Vender','Vender'),
('tienda-ropa','ticket','Ticket','Tickets'),
('tienda-ropa','inventario','Prenda','Prendas'),
('tienda-ropa','producto','Prenda','Prendas'),
-- zapateria
('zapateria','cliente','Cliente','Clientes'),
('zapateria','venta','Vender','Vender'),
('zapateria','ticket','Ticket','Tickets'),
('zapateria','inventario','Calzado','Calzado'),
('zapateria','producto','Par de zapatos','Pares de zapatos'),
-- muebleria
('muebleria','cliente','Cliente','Clientes'),
('muebleria','venta','Vender','Vender'),
('muebleria','ticket','Nota','Notas'),
('muebleria','inventario','Mueble','Muebles'),
('muebleria','producto','Mueble','Muebles')
ON CONFLICT (giro_slug, clave) DO UPDATE SET
  valor_singular = EXCLUDED.valor_singular,
  valor_plural = EXCLUDED.valor_plural,
  updated_at = now();

COMMIT;

-- ─────────────────────────────────────────────────────────────────────────
-- SECTION 3: giros_campos
-- 7 giros × N producto-modal fields = 48 rows
-- modal='producto', visible=true, requerido=field.required||false,
-- orden = (index+1)*10, label_override=field.label
-- ─────────────────────────────────────────────────────────────────────────
BEGIN;

INSERT INTO giros_campos (giro_slug, modal, campo, visible, requerido, orden, label_override) VALUES
-- farmacia (9)
('farmacia','producto','active_ingredient',true,false,10,'Ingrediente activo'),
('farmacia','producto','concentration',true,false,20,'Concentración'),
('farmacia','producto','presentation',true,false,30,'Presentación'),
('farmacia','producto','patent_or_generic',true,false,40,'Patente / genérico'),
('farmacia','producto','lot',true,true,50,'Lote'),
('farmacia','producto','expiry',true,true,60,'Caducidad'),
('farmacia','producto','requires_prescription',true,false,70,'Requiere receta médica'),
('farmacia','producto','controlled_substance',true,false,80,'Sustancia controlada'),
('farmacia','producto','sanitary_register',true,false,90,'Registro COFEPRIS'),
-- refaccionaria (10)
('refaccionaria','producto','part_number',true,true,10,'Número de parte'),
('refaccionaria','producto','oem',true,false,20,'OEM'),
('refaccionaria','producto','brand',true,false,30,'Marca refacción'),
('refaccionaria','producto','vehicle_brand',true,false,40,'Marca auto'),
('refaccionaria','producto','vehicle_model',true,false,50,'Modelo'),
('refaccionaria','producto','year',true,false,60,'Año'),
('refaccionaria','producto','engine',true,false,70,'Motor'),
('refaccionaria','producto','transmission',true,false,80,'Transmisión'),
('refaccionaria','producto','fuel',true,false,90,'Combustible'),
('refaccionaria','producto','warranty',true,false,100,'Garantía'),
-- veterinaria (7)
('veterinaria','producto','pet_species',true,false,10,'Especie'),
('veterinaria','producto','active_ingredient',true,false,20,'Ingrediente activo'),
('veterinaria','producto','concentration',true,false,30,'Concentración'),
('veterinaria','producto','lot',true,false,40,'Lote'),
('veterinaria','producto','expiry',true,false,50,'Caducidad'),
('veterinaria','producto','requires_prescription',true,false,60,'Requiere receta veterinaria'),
('veterinaria','producto','weight_range',true,false,70,'Rango de peso'),
-- floreria (6)
('floreria','producto','flower_type',true,false,10,'Tipo de flor'),
('floreria','producto','arrangement_type',true,false,20,'Tipo de arreglo'),
('floreria','producto','requires_delivery',true,false,30,'Requiere entrega a domicilio'),
('floreria','producto','occasion',true,false,40,'Ocasión'),
('floreria','producto','colors',true,false,50,'Colores'),
('floreria','producto','freshness_days',true,false,60,'Días de duración estimados'),
-- panaderia (5)
('panaderia','producto','price_per_kilo',true,false,10,'Precio por kilo'),
('panaderia','producto','allergens',true,false,20,'Alérgenos'),
('panaderia','producto','has_gluten',true,false,30,'Con gluten'),
('panaderia','producto','production_date',true,false,40,'Fecha elaboración'),
('panaderia','producto','expiry',true,false,50,'Caducidad'),
-- carniceria (6)
('carniceria','producto','cut',true,false,10,'Corte'),
('carniceria','producto','animal_origin',true,false,20,'Origen animal'),
('carniceria','producto','price_per_kilo',true,true,30,'Precio por kilo'),
('carniceria','producto','lot',true,false,40,'Lote'),
('carniceria','producto','expiry',true,false,50,'Caducidad'),
('carniceria','producto','frozen',true,false,60,'Congelado'),
-- tienda-ropa (5)
('tienda-ropa','producto','brand',true,false,10,'Marca'),
('tienda-ropa','producto','size',true,false,20,'Talla'),
('tienda-ropa','producto','color',true,false,30,'Color'),
('tienda-ropa','producto','gender',true,false,40,'Género'),
('tienda-ropa','producto','season',true,false,50,'Temporada')
ON CONFLICT (giro_slug, modal, campo) DO UPDATE SET
  visible = EXCLUDED.visible,
  requerido = EXCLUDED.requerido,
  orden = EXCLUDED.orden,
  label_override = EXCLUDED.label_override,
  updated_at = now();

COMMIT;

-- ─────────────────────────────────────────────────────────────────────────
-- END seed. Re-run is safe (all UPSERTs).
-- ─────────────────────────────────────────────────────────────────────────
Cliente','
